version: '3.8'

services:

    micro_01:
        build:
            args:
                user: leandro
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: laravel-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on:
            - redis_micro_01
            - queue
        networks:
            - microservices

    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "8000:80"
            - "443:443"
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d
        networks:
            - microservices

    db_micro_01:
        image: mysql:5.7.22
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        volumes:
            - ./.docker/mysql/dbdata:/var/lib/mysql
        ports:
            - "3308:3306"
        networks:
            - microservices

    redis_micro_01:
        image: redis:alpine
        restart: unless-stopped
        ports:
            - "6378:6379"
        networks:
            - microservices

    queue:
        build:
            args:
                user: leandro
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        restart: unless-stopped
        command: php artisan queue:work
        ports:
            - "9001:9000"
        volumes:
            - ./:/var/www
        depends_on:
            - redis_micro_01
        networks:
            - microservices

networks:
    microservices:
        driver: bridge
